### ISSUE TITLE
номер пина

### ISSUE THREAD

**Issue by mikhailrojo** [alexbadaloff/esp8266_mh_z19#1]
кажется номер пина на схеме 6, а в коде 6... может быть ошибка?

**Comment by alexbadaloff** [comment]
Имеется ввиду D6? Так обозначаются пины на плате esp8266. Чтобы к ним обратиться в коде, нужно указывать номер gpio. Пину D6 соответствует gpio12. Я к нему и обращаюсь.
`#define pwmPin 12 // gpio12`
